// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Z-bit Systems, LLC

#include "pair_adapter.h"

#include "osdp_pair_pqclean.h"

/* Generated by osdp-pair-provision into the build directory; see this tool's
 * CMakeLists. Not checked in, so it can never drift from the port that
 * issued it. */
#include "pair_credentials.h"

#include <stdio.h>
#include <string.h>

/* ---- Entropy -----------------------------------------------------------
 *
 * The PQClean port supplies no default on purpose, so this is where the
 * tool's ML-KEM keys and pairing nonces actually come from. Both platforms
 * below are OS CSPRNGs; a failure is reported rather than papered over,
 * because the alternative is a pairing exchange that completes and yields a
 * guessable SCBK. */

#if defined(_WIN32)

#define _CRT_RAND_S
#include <stdlib.h>

static int os_rand(uint8_t *out, size_t n)
{
    /* rand_s draws from the OS CSPRNG (RtlGenRandom underneath), so it needs
     * no extra link dependency the way BCryptGenRandom would. */
    size_t i = 0;
    while (i < n) {
        unsigned int v = 0;
        if (rand_s(&v) != 0) {
            return -1;
        }
        for (size_t b = 0; b < sizeof(v) && i < n; b++) {
            out[i++] = (uint8_t)(v >> (b * 8));
        }
    }
    return 0;
}

#else

#include <stdio.h>

static int os_rand(uint8_t *out, size_t n)
{
    FILE *f = fopen("/dev/urandom", "rb");
    if (f == NULL) {
        return -1;
    }
    const size_t got = fread(out, 1, n, f);
    (void)fclose(f);
    return (got == n) ? 0 : -1;
}

#endif

/* ---- Pairing wiring ----------------------------------------------------- */

static osdp_pair_pqclean_ctx_t s_ctx;
static osdp_pair_crypto_t      s_crypto;

const char *pd_mock_pair_subject(void)
{
    return OSDP_PAIR_CREDENTIALS_SUBJECT;
}

bool pd_mock_pair_attach(osdp_pd_t *pd, osdp_pd_pair_t *pair)
{
    osdp_pair_pqclean_set_rand(os_rand);

    /* Prove entropy works before anything depends on it. Discovering a dead
     * CSPRNG part-way through a handshake would surface as an opaque crypto
     * error on the wire. */
    uint8_t probe[32];
    if (os_rand(probe, sizeof(probe)) != 0) {
        fprintf(stderr, "osdp-pd-mock: no OS entropy source; pairing refused\n");
        return false;
    }

    osdp_pair_pqclean_crypto_init(&s_crypto, &s_ctx);
    if (osdp_pair_pqclean_set_dsa(&s_ctx, osdp_pair_device_pk,
                                  osdp_pair_device_sk,
                                  sizeof(osdp_pair_device_sk)) != OSDP_OK) {
        fprintf(stderr, "osdp-pd-mock: built-in pairing credential rejected\n");
        return false;
    }

    const osdp_pair_local_t local = {
        osdp_pair_device_cert, sizeof(osdp_pair_device_cert)
    };
    const osdp_pair_trust_t trust = { .ca_pubkey = osdp_pair_ca_pk };

    osdp_pd_pair_init(pair, &s_crypto, &local, &trust);
    osdp_pd_attach_pair(pd, pair);
    return true;
}
