// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Z-bit Systems, LLC

/* Capture-replay validation against an independent OSDP-SC implementation.
 *
 * The frames embedded below are extracted byte-for-byte from
 * tests/captures/sc-monitor-current.osdpcap, recorded by SIA's
 * `libosdp-conformance 1.38-4` running as a passive monitor while a
 * real ACU and a real PD established a Secure Channel session over
 * RS-485. The PD in that capture used:
 *
 *   - SCBK-D (the spec's well-known default install key — selector 0
 *     in the SCS_11 / SCS_13 SEC_BLK_DATA[0] byte).
 *   - cUID 0a 00 17 03 00 ca fe de (the leading 8 bytes of its PDID).
 *   - RND.B = "abcdefgh" (0x61..0x68). libosdp-conformance does not
 *     randomise this on every handshake — it uses a fixed sequence,
 *     which is convenient for replay.
 *
 * If our PD is correct, configuring it with the same SCBK-D, the same
 * cUID, and a PRNG that emits the same RND.B should make it produce
 * byte-identical CCRYPT and RMAC_I replies in response to the captured
 * CHLNG and SCRYPT commands. Any divergence — even one bit — points to
 * a spec-interpretation bug somewhere in keys / cryptograms / frame
 * layout / CRC.
 *
 * This is a stricter check than the existing unit tests: those use our
 * own primitives on both sides of the comparison, so a consistent bug
 * in (say) S-ENC derivation would be invisible. Here, the captured
 * CCRYPT bytes were generated by an independent codebase against the
 * same spec, so a matching output validates both implementations
 * against each other AND against the spec.
 */

#include "osdp/osdp_frame.h"
#include "osdp/osdp_pd.h"
#include "osdp/osdp_sc.h"
#include "sc_test_aes.h"
#include "unity.h"

#include <string.h>

/* ---- Captured frames (from tests/captures/sc-monitor-current.osdpcap)
 *
 * Lines 6–9 of the capture: the first SC-CS handshake. The ACU
 * (libosdp-conformance) sends CHLNG, our PD responds with CCRYPT, the
 * ACU sends SCRYPT, our PD responds with RMAC_I. */

/* Line 6: CHLNG (SCS_11) — ACU→PD.
 *   ctrl=0x0d (SQN=1, CRC, SCB present)
 *   SCB = 03 11 00 = len=3, type=SCS_11, selector=0 (SCBK-D)
 *   code = 0x76 (osdp_CHLNG)
 *   payload (RND.A) = cd cd 92 12 12 d3 ee 6a
 *   CRC = 8c 8b */
static const uint8_t kCapturedChlng[] = {
    0x53, 0x00, 0x13, 0x00, 0x0d, 0x03, 0x11, 0x00, 0x76,
    0xcd, 0xcd, 0x92, 0x12, 0x12, 0xd3, 0xee, 0x6a,
    0x8c, 0x8b
};

/* Line 7: CCRYPT (SCS_12) — PD→ACU.
 *   ctrl=0x0d, SCB = 03 12 00, code = 0x76 (osdp_CCRYPT)
 *   payload = cUID(8) || RND.B(8) || ClientCryptogram(16) = 32 bytes
 *     cUID            = 0a 00 17 03 00 ca fe de
 *     RND.B           = 61 62 63 64 65 66 67 68 ("abcdefgh")
 *     ClientCryptogram = 4b 7e 2f 98 ad 79 bd 96 81 19 a8 d1 d3 db da ee
 *   CRC = 8e fd */
static const uint8_t kExpectedCcrypt[] = {
    0x53, 0x80, 0x2b, 0x00, 0x0d, 0x03, 0x12, 0x00, 0x76,
    0x0a, 0x00, 0x17, 0x03, 0x00, 0xca, 0xfe, 0xde,
    0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x67, 0x68,
    0x4b, 0x7e, 0x2f, 0x98, 0xad, 0x79, 0xbd, 0x96,
    0x81, 0x19, 0xa8, 0xd1, 0xd3, 0xdb, 0xda, 0xee,
    0x8e, 0xfd
};

/* Line 8: SCRYPT (SCS_13) — ACU→PD.
 *   ctrl=0x0e (SQN=2), SCB = 03 13 00, code = 0x77 (osdp_SCRYPT)
 *   payload (ServerCryptogram) = a2 30 f5 d3 3b 25 f4 34 34 92 9a b2 08 de 90 a7
 *   CRC = 41 03 */
static const uint8_t kCapturedScrypt[] = {
    0x53, 0x00, 0x1b, 0x00, 0x0e, 0x03, 0x13, 0x00, 0x77,
    0xa2, 0x30, 0xf5, 0xd3, 0x3b, 0x25, 0xf4, 0x34,
    0x34, 0x92, 0x9a, 0xb2, 0x08, 0xde, 0x90, 0xa7,
    0x41, 0x03
};

/* Line 9: RMAC_I (SCS_14) — PD→ACU.
 *   ctrl=0x0e, SCB = 03 14 01 (status = ok), code = 0x78 (osdp_RMAC_I)
 *   payload (Initial R-MAC) = d8 f5 43 e2 07 ac 5d 2e 30 be 9f ac 3a a0 4b ea
 *   CRC = 95 85 */
static const uint8_t kExpectedRmacI[] = {
    0x53, 0x80, 0x1b, 0x00, 0x0e, 0x03, 0x14, 0x01, 0x78,
    0xd8, 0xf5, 0x43, 0xe2, 0x07, 0xac, 0x5d, 0x2e,
    0x30, 0xbe, 0x9f, 0xac, 0x3a, 0xa0, 0x4b, 0xea,
    0x95, 0x85
};

/* PD configuration matching the captured peer. */
static const uint8_t kCapturedCuid[OSDP_SC_CUID_LEN] = {
    0x0a, 0x00, 0x17, 0x03, 0x00, 0xca, 0xfe, 0xde,
};
static const uint8_t kCapturedRndB[OSDP_SC_RND_LEN] = {
    0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x67, 0x68,
};
#define CAPTURED_PD_ADDRESS 0x00U

/* ---- Mock transport ----------------------------------------------------- */

#define MOCK_BUF_LEN 1024U

typedef struct mock_transport {
    uint8_t  incoming[MOCK_BUF_LEN];
    size_t   incoming_len;
    size_t   incoming_off;
    uint8_t  outgoing[MOCK_BUF_LEN];
    size_t   outgoing_len;
    uint32_t now_ms;
} mock_transport_t;

static int mock_read(void *user, uint8_t *buf, size_t cap)
{
    mock_transport_t *m = (mock_transport_t *)user;
    if (m->incoming_off > m->incoming_len) {
        return 0;
    }
    const size_t avail = m->incoming_len - m->incoming_off;
    const size_t n = (cap < avail) ? cap : avail;
    if (n > 0) {
        (void)memcpy(buf, &m->incoming[m->incoming_off], n);
        m->incoming_off += n;
    }
    return (int)n;
}

static int mock_write(void *user, const uint8_t *buf, size_t len)
{
    mock_transport_t *m = (mock_transport_t *)user;
    const size_t free_room = MOCK_BUF_LEN - m->outgoing_len;
    const size_t n = (len < free_room) ? len : free_room;
    if (n > 0) {
        (void)memcpy(&m->outgoing[m->outgoing_len], buf, n);
        m->outgoing_len += n;
    }
    return (int)n;
}

static uint32_t mock_now_ms(void *user)
{
    return ((const mock_transport_t *)user)->now_ms;
}

static void mock_init(mock_transport_t *m, osdp_pd_transport_t *t)
{
    (void)memset(m, 0, sizeof(*m));
    t->read   = mock_read;
    t->write  = mock_write;
    t->now_ms = mock_now_ms;
    t->user   = m;
}

static void mock_load_incoming(mock_transport_t *m,
                               const uint8_t *bytes, size_t len)
{
    TEST_ASSERT_LESS_OR_EQUAL_size_t(MOCK_BUF_LEN, len);
    (void)memcpy(m->incoming, bytes, len);
    m->incoming_len = len;
    m->incoming_off = 0;
}

/* ---- PD setup ----------------------------------------------------------- */

/* Build a PD that mirrors the captured peer's configuration: address
 * 0, SCBK-D as the only SC key, cUID matching the capture, and a PRNG
 * pinned to emit the captured RND.B on every call. */
static void configure_replay_pd(osdp_pd_t *pd,
                                mock_transport_t *m,
                                osdp_pd_transport_t *t)
{
    sc_test_crypto_set_fixed_rand(kCapturedRndB, sizeof(kCapturedRndB));

    mock_init(m, t);
    osdp_pd_init(pd, CAPTURED_PD_ADDRESS);
    osdp_pd_set_transport (pd, t);
    osdp_pd_set_sc_crypto (pd, sc_test_crypto_tiny_aes());
    osdp_pd_set_sc_scbk_d (pd, OSDP_SCBK_DEFAULT);
    osdp_pd_set_sc_cuid   (pd, kCapturedCuid);
}

void setUp(void) {}
void tearDown(void)
{
    /* Restore LCG mode so subsequent tests in other binaries don't see
     * lingering fixed-rand state if the static lib gets reused. */
    sc_test_crypto_set_fixed_rand(NULL, 0);
}

/* The PD now prepends spec-5.7 marking byte(s) ahead of the SOM, which
 * the captured reference frames (taken from a device that didn't emit
 * them) lack. Assert the PD's output is the marking followed by a
 * byte-identical copy of the captured frame. */
static void assert_outgoing_is_marked_capture(const mock_transport_t *m,
                                              const uint8_t *captured,
                                              size_t captured_len)
{
    TEST_ASSERT_EQUAL_size_t(OSDP_FRAME_MARK_LEN + captured_len,
                             m->outgoing_len);
    TEST_ASSERT_EQUAL_MEMORY(captured, m->outgoing + OSDP_FRAME_MARK_LEN,
                             captured_len);
}

/* ---- Tests --------------------------------------------------------------- */

/* Step 1 of the handshake: replay CHLNG, expect byte-identical CCRYPT. */
static void test_chlng_replay_yields_identical_ccrypt(void)
{
    mock_transport_t m;
    osdp_pd_transport_t t;
    osdp_pd_t pd;
    configure_replay_pd(&pd, &m, &t);

    mock_load_incoming(&m, kCapturedChlng, sizeof(kCapturedChlng));
    osdp_pd_tick(&pd);

    assert_outgoing_is_marked_capture(&m, kExpectedCcrypt,
                                      sizeof(kExpectedCcrypt));
    TEST_ASSERT_FALSE(osdp_pd_sc_established(&pd));
}

/* Step 2: replay both CHLNG (to set up state) and SCRYPT, expect
 * byte-identical RMAC_I, and the session established. */
static void test_full_handshake_replay_yields_identical_rmac_i(void)
{
    mock_transport_t m;
    osdp_pd_transport_t t;
    osdp_pd_t pd;
    configure_replay_pd(&pd, &m, &t);

    /* CHLNG → CCRYPT. */
    mock_load_incoming(&m, kCapturedChlng, sizeof(kCapturedChlng));
    osdp_pd_tick(&pd);
    assert_outgoing_is_marked_capture(&m, kExpectedCcrypt,
                                      sizeof(kExpectedCcrypt));

    /* Drain the CCRYPT bytes from outgoing so the next assertion can
     * see RMAC_I cleanly. */
    m.outgoing_len = 0;

    /* SCRYPT → RMAC_I. */
    mock_load_incoming(&m, kCapturedScrypt, sizeof(kCapturedScrypt));
    osdp_pd_tick(&pd);
    assert_outgoing_is_marked_capture(&m, kExpectedRmacI,
                                      sizeof(kExpectedRmacI));

    /* Session is now established; both MAC chain entries seeded with
     * the captured Initial R-MAC. */
    TEST_ASSERT_TRUE(osdp_pd_sc_established(&pd));
    static const uint8_t kInitialRmac[OSDP_SC_MAC_LEN] = {
        0xd8, 0xf5, 0x43, 0xe2, 0x07, 0xac, 0x5d, 0x2e,
        0x30, 0xbe, 0x9f, 0xac, 0x3a, 0xa0, 0x4b, 0xea,
    };
    TEST_ASSERT_EQUAL_MEMORY(kInitialRmac,
                             pd.sc.session.last_outbound_mac,
                             OSDP_SC_MAC_LEN);
    TEST_ASSERT_EQUAL_MEMORY(kInitialRmac,
                             pd.sc.session.last_inbound_mac,
                             OSDP_SC_MAC_LEN);
}

int main(void)
{
    UNITY_BEGIN();
    RUN_TEST(test_chlng_replay_yields_identical_ccrypt);
    RUN_TEST(test_full_handshake_replay_yields_identical_rmac_i);
    return UNITY_END();
}
